services:
  chsmonitoring.api:
    networks:
      - shared
    container_name: monitoring_service_container
    restart: always
    build:
      context: .
      dockerfile: CHSMonitoring.API/Dockerfile
    ports:
      - 8091:8080
    environment:
      - DEFAULT_CONNECTION_STRING=Server=postgres_container;Database=monitoring_db_ver3;User ID=postgres;Password=-pl,mju7
    depends_on:
      - postgres
  
  chsmonitoring.client:
    networks:
      - shared
    container_name: monitoring_client_container
    restart: always
    build:
      context: ../monitoringkrasnoyarskclient
      dockerfile: ../monitoringkrasnoyarskclient/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - chsmonitoring.api
      - proxy-nginx
  
  proxy-nginx:
    networks:
      - shared
    container_name: proxy-nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  postgres:
    networks:
      - shared
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: -pl,mju7
      POSTGRES_DB: monitoring_db_ver3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    depends_on:
      - pgadmin
  
  pgadmin:
    networks:
      - shared
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
networks:
  shared:
    driver: bridge
volumes:
  postgres-data: