using System.ComponentModel;

namespace CHSMonitoringKrasnoyarsk.Models;

public enum StreetNameEnum
{
    [Description("1905 года")] OneNineZeroFiveYears,
    [Description("26 Бакинских комиссаров")] TwentySixBakinskikhKomissarov,
    [Description("3 Августа")] ThreeAugusta,
    [Description("30 Июля")] ThirtyJuly,
    [Description("40 лет Победы")] FortyYearsOfVictory,
    [Description("52-й квартал")] FiftySecondQuarter,
    [Description("60 лет образования СССР")] SixtyYearsOfTheSSR,
    [Description("60 лет Октября")] SixtyYearsOfOctober,
    [Description("78 Добровольческой Бригады")] SeventyEightDobrovolskoyBrigady,
    [Description("8 Марта")] EightMarch,
    [Description("9 Мая")] NineMay,
    [Description("9 Января")] NineJanuary,
    [Description("Абазинский")] Abazinsky,
    [Description("Абытаевская")] Abytayevskaya,
    [Description("Авамский")] Avamskoy,
    [Description("Авиаторов")] Aviatorov,
    [Description("Автобусный")] Avtobusny,
    [Description("Автомобилистов")] Automobiliystov,
    [Description("Ады Лебедевой")] AdyLebedevoy,
    [Description("Айвазовского")] Ayvazovskogo,
    [Description("Академгородок")] Akademgorodok,
    [Description("Академика Вавилова")] AkademikaVavilova,
    [Description("Академика Киренского")] AkademikaKirenskogo,
    [Description("Академика Курчатова")] AkademikaKurchatova,
    [Description("Академика Павлова")] AkademikaPavlova,
    [Description("Акционерная")] Akcionskaya,
    [Description("Александра Матросова")] AleksandraMatrosova,
    [Description("Александровский")] Aleksandrovskoy,
    [Description("Алексеева")] Alekseeva,
    [Description("Алексея Асеева")] AlekseeaAseeva,
    [Description("Алеши Тимошенкова")] AlashiTimoshenkova,
    [Description("Алыкельская")] Alykelskaya,
    [Description("Амурская")] Amurskaya,
    [Description("Анабарская")] Anabarskaya,
    [Description("Анатолия Гладкова")] AnatolyaGladkova,
    [Description("Ангарская")] Angarskaya,
    [Description("Андрея Дубенского")] AndreyaDubenskogo,
    [Description("Апрельская")] Aprilskaya,
    [Description("Аральская")] Aralskaya,
    [Description("Арейская")] Areyskaya,
    [Description("Аринская")] Arinskaya,
    [Description("Армейская")] Armeyskaya,
    [Description("Астраханская")] Astrahanskaya,
    [Description("Афанасия Тавакова")] AfanasiyaTavakova,
    [Description("Афонтовский")] Afontovsky,
    [Description("Аэровокзальная")] Aerovokzalnaya,
    [Description("Бабушкина")] Babushkina,
    [Description("Базайская")] Bazayskaya,
    [Description("Базарная")] Bazarnaya,
    [Description("Батурина")] Baturnina,
    [Description("Баумана")] Baumana,
    [Description("Башиловская")] Bashilovskaya,
    [Description("Бебеля")] Bebelia,
    [Description("Белинского")] Belinskogo,
    [Description("Белорусская")] Belaruskaya,
    [Description("Березина")] Berezina,
    [Description("Бийская")] Biyskaya,
    [Description("Бограда")] Bograda,
    [Description("Богучанская")] Boguchanskaya,
    [Description("Большой")] Bolshoy,
    [Description("Борисевича")] Borisovicha,
    [Description("Борисова")] Borisova,
    [Description("Бородинская")] Borodinskaya,
    [Description("Ботаническая")] Botanicheskaya,
    [Description("Ботанический бульвар")] BotanicheskoyBulvar,
    [Description("Боткина")] Botkina,
    [Description("Братьев Абалаковых")] BratevAbalakovyh,
    [Description("Брянская")] Bryanskaya,
    [Description("Быковского")] Bykovskogo,
    [Description("Васильковый")] Vasilkovoy,
    [Description("Вейнбаума")] Veinbauma,
    [Description("Вербная")] Verbnaya,
    [Description("Верхняя")] Verkhnyaya,
    [Description("Весны")] Vesny,
    [Description("Взлетная")] Vzletnaya,
    [Description("Вильского")] Vilskogo,
    [Description("Вишнёвый")] Vishnevoy,
    [Description("Водомётный переулок")] VodometnyyPerewulok,
    [Description("Водопьянова")] Vodopianova,
    [Description("Водянникова")] Vodyannikova,
    [Description("Вокзальная")] Vokzalnaya,
    [Description("Волгоградская")] Volgogradskaya,
    [Description("Волжская")] Volzhskaya,
    [Description("Волочаевская")] Volochaevskaya,
    [Description("Воронова")] Voronova,
    [Description("Вузовский")] Vuzovsky,
    [Description("Высотная")] Vysotnaya,
    [Description("Гагарина")] Gagarina,
    [Description("Гайдашевка")] Gaydasevka,
    [Description("Гастелло")] Gastello,
    [Description("Герцена")] Hercena,
    [Description("Глинки")] Glinki,
    [Description("Говорова")] Govorova,
    [Description("Гоголя")] Gogolya,
    [Description("Годенко")] Godenko,
    [Description("Горького")] Gorikogo,
    [Description("Графитная")] Grafitnaya,
    [Description("Гриболевская")] Gribolevskaya,
    [Description("Грунтовая")] Gruntovaya,
    [Description("Грушевая")] Grushkaya,
    [Description("Гусарова")] Gusarova,
    [Description("Давыдова")] Davydova,
    [Description("Дальневосточная")] Dalnevostochnaya,
    [Description("Дальняя")] Dalnyaya,
    [Description("Даурская")] Daurskaya,
    [Description("Дачная")] Dachnaya,
    [Description("Декабристов")] Dekabrystov,
    [Description("Демьяна Бедного")] DemianBednogo,
    [Description("Деповская")] Depovskaya,
    [Description("Джамбульская")] Dzhambulskaya,
    [Description("Дзержинского")] Dzerzhinskogo,
    [Description("Диктатуры Пролетариата")] DiktaturyProletariata,
    [Description("Дмитрия Мартынова")] DmitriyMartynova,
    [Description("Добролюбова")] Dobrolyubova,
    [Description("Дубровинского")] Dubrovinskogo,
    [Description("Дудинская")] Dudinskaya,
    [Description("Елены Стасовой")] ElenyStasovoy,
    [Description("Емельяновская")] Emelyanovskaya,
    [Description("Енисейская")] Eniseiskaya,
    [Description("Железнодорожников")] Zheleznodorozhnikov,
    [Description("Забобонова")] Zabobonova,
    [Description("Заводская")] Zavodskaya,
    [Description("Загородная")] Zagorodnaya,
    [Description("Зарничная")] Zarnichnaya,
    [Description("Затонская")] Zatonskaya,
    [Description("Защитников Ленинграда")] ZashchitnikovLeninograda,
    [Description("Зои Космодемьянской")] ZoiKosmodemyanskoy,
    [Description("Ивченко")] Ivchenko,
    [Description("Игарская")] Igarskaya,
    [Description("Изумрудная")] Izumrudnaya,
    [Description("Иркутская")] Irkutskaya,
    [Description("Историческая")] Istoriiskaya,
    [Description("Казарменный")] Kazarmennyy,
    [Description("Калинина")] Kalinina,
    [Description("Калиновая")] Kalinovaya,
    [Description("Камская")] Kamskaya,
    [Description("Кандагарская")] Kandagarskaya,
    [Description("Капитанская")] Kapitanskaya,
    [Description("Карамзина")] Karamzina,
    [Description("Каратанова")] Karatanova,
    [Description("Караульная")] Karaulnaya,
    [Description("Карбышева")] Karbysheva,
    [Description("Кардачинская")] Kardachinskaya,
    [Description("Карла Маркса")] KarlMarksa,
    [Description("Качинская")] Kachinskaya,
    [Description("Квартальная")] Kvartalnaya,
    [Description("Кедровый")] Kedrovyy,
    [Description("Кипрейная")] Kipreynaya,
    [Description("Кирова")] Kirova,
    [Description("Кишиневская")] Kishevskaya,
    [Description("Клеверный")] Kleverny,
    [Description("Ключевская")] Klyuchevskaya,
    [Description("Коломенская")] Kolomenskaya,
    [Description("Кольцевая")] Koltevaya,
    [Description("Комарова")] Komarova,
    [Description("Комбайностроителей")] Kombaynostritelya,
    [Description("Коммунальная")] Kommunalnaya,
    [Description("Комсомольский")] Komsomolskoy,
    [Description("Конституции СССР")] KonstituciiSSSR,
    [Description("Копылова")] Kopilova,
    [Description("Корабельная")] Korabelnaya,
    [Description("Корнеева")] Korneeva,
    [Description("Корнетова")] Kornetova,
    [Description("Королева")] Koroleva,
    [Description("Короленко")] Korolenko,
    [Description("Космонавтов")] Kosmonavtov,
    [Description("Котовского")] Kotovskogo,
    [Description("Кочубея")] Kochubeya,
    [Description("Кравченко")] Kravchenko,
    [Description("Крайняя")] Kraynaya,
    [Description("Красная площадь")] KrasnayaPloshchad,
    [Description("Краснодарская")] Krasnodarskaya,
    [Description("Красной Армии")] KrasnoyArmii,
    [Description("Красной Гвардии")] KrasnoyGvardii,
    [Description("Красномосковская")] Krasnomoskovskaya,
    [Description("Краснопресненская")] Krasnopresnenskaya,
    [Description("Краснофлотская 2-ая")] Krasnoflotskaya2Aya,
    [Description("Красноярский рабочий")] KrasnoyarskoyRabochiy,
    [Description("Крупской")] Krupskoy,
    [Description("Крылова")] Krylova,
    [Description("Куйбышева")] Kuibysheva,
    [Description("Курганская")] Kurganskaya,
    [Description("Кутузова")] Kutuzova,
    [Description("Ладо Кецховели")] LadoKetskhoveli,
    [Description("Ламская")] Lamskaya,
    [Description("Ленина")] Lenina,
    [Description("Ленинградская")] Leninogradskaya,
    [Description("Лесопарковая")] Lesoparkovaya,
    [Description("Лесопильщиков")] Lesopilshchikov,
    [Description("Лиды Прушинской")] LidyPrushinskoy,
    [Description("Линейная")] Lineynaya,
    [Description("Лиственная")] Lisvennaya,
    [Description("Литейная")] Liteynaya,
    [Description("Ломоносова")] Lomnosova,
    [Description("Львовская")] Lvovskaya,
    [Description("Любы Шевцовой")] LyubyShevtsovy,
    [Description("Маерчака")] Maerchaka,
    [Description("Малаховская")] Malahovskaya,
    [Description("Малиновского")] Malinovskogo,
    [Description("Марии Цукановой")] MariyTsukanovoy,
    [Description("Марковского")] Markovskogo,
    [Description("Мате Залки")] MateZalki,
    [Description("Машиностроителей")] Mashinostritelya,
    [Description("Маяковского")] Mayakovskogo,
    [Description("Медицинский")] Medicinskoy,
    [Description("Менжинского")] Menzhinskogo,
    [Description("Металлургов")] Metallurgov,
    [Description("Мечникова")] Mechnikova,
    [Description("Микуцкого")] Mikutskogo,
    [Description("Минина")] Minina,
    [Description("Мира")] Mira,
    [Description("Мирошниченко")] Miroshnichenko,
    [Description("Мичурина")] Michurina,
    [Description("Можайского")] Mozhaiskogo,
    [Description("Молодежный")] Molodezhnyy,
    [Description("Молокова")] Molokova,
    [Description("Московская")] Moskovskaya,
    [Description("Мужества")] Muzhestva,
    [Description("Навигационная")] Navigatsionnaya,
    [Description("Нерчинская")] Nercinskaya,
    [Description("Никитина")] Nikitina,
    [Description("Николаева")] Nikolaeva,
    [Description("Новая")] Novaya,
    [Description("Новая Заря")] NovayaZarya,
    [Description("Новгородская")] Novgorodskaya,
    [Description("Новомлинская")] Novominskaya,
    [Description("Новороссийская")] Novorossiyskaya,
    [Description("Новосибирская")] Novosibirskaya,
    [Description("Норильская")] Norilskaya,
    [Description("Обороны")] Oborony,
    [Description("Огородная 2-ая")] Ogordnaya2Aya,
    [Description("Одесская")] Odessa,
    [Description("Озерная")] Ozernaya,
    [Description("Октябрьская")] Oktyabrskaya,
    [Description("Олейникова")] Oleynikova,
    [Description("Омская")] Omskaya,
    [Description("Офицерская")] Ofitserskaya,
    [Description("Охраны труда")] OhranyTrudy,
    [Description("Панфиловцев")] Panfilovtsyev,
    [Description("Парадовского")] Paradovskogo,
    [Description("Парашютная")] Parashytnaya,
    [Description("Парижской коммуны")] PariskoyKommuni,
    [Description("Парковая")] Parkovaya,
    [Description("Паровозная")] Parovoznaya,
    [Description("Партизана Железняка")] PartizanaZheliznyaka,
    [Description("Партизанская")] Partizanskaya,
    [Description("Парусная")] Parusnaya,
    [Description("Пархоменко")] Parhomenko,
    [Description("Пастеровская")] Pasterovskaya,
    [Description("Пасхальная")] Pashalnaya,
    [Description("Перенсона")] Perensona,
    [Description("Песочная")] Pesochnaya,
    [Description("Петра Ломако")] PetraLomako,
    [Description("Петра Подзолкова")] PetraPodzolkova,
    [Description("Петра Словцова")] PetraSlowtcova,
    [Description("Петрушина")] Petrushina,
    [Description("Пионерской правды")] PionerskoyPravdy,
    [Description("Пирогова")] Pirogov,
    [Description("Пихтовая")] Pihytnaya,
    [Description("Побежимова")] Pobezhimova,
    [Description("Пожарского")] Pozharskogo,
    [Description("Пойменный")] Poimennyy,
    [Description("Ползунова")] Polzunova,
    [Description("Полигонная")] Poligonnaya,
    [Description("Полтавская")] Poltavskaya,
    [Description("Попова")] Popova,
    [Description("Пржевальского")] Przhevalskogo,
    [Description("Прибойная")] Priboynaya,
    [Description("Пролетарская")] Proletarskaya,
    [Description("Промысловая")] Promyslovaya,
    [Description("Профсоюзов")] Profsoyuzov,
    [Description("Пушкина")] Pushkina,
    [Description("Пясинская")] Pyasinskaya,
    [Description("Рейдовая")] Reydovaya,
    [Description("Ремесленная")] Remeslennaya,
    [Description("Республики")] Respubliki,
    [Description("Речной")] Rechnoy,
    [Description("Робеспьера")] Robespiera,
    [Description("Рокоссовского")] Rokossovskogo,
    [Description("Ромашковый")] Romashkovyy,
    [Description("Рязанская")] Ryazanskaya,
    [Description("Сады")] Sady,
    [Description("Санаторная")] Sanatornaya,
    [Description("Саянская")] Sayanskaya,
    [Description("Свердловская")] Sverdlovskaya,
    [Description("Светлова")] Svetlova,
    [Description("Светлогорская")] Svetlogorskaya,
    [Description("Светлогорский")] Svetlogorskoy,
    [Description("Свободная")] Svobodnaya,
    [Description("Свободный")] Svobodnyy,
    [Description("Северная")] Severnaya,
    [Description("Северный проезд")] SevernyyProezd,
    [Description("Северо-Енисейская")] SeveroEniseyskaya,
    [Description("Седова")] Sedova,
    [Description("Семафорная")] Semafornaya,
    [Description("Сергея Куликова")] SergiyaKulikova,
    [Description("Сергея Лазо")] SergiyaLazo,
    [Description("Серебряный бор")] SerbrynnyyBor,
    [Description("Серова")] Serova,
    [Description("Сеченова")] Sechenova,
    [Description("Сибирский")] Sibirskoy,
    [Description("Скальная")] Skalnaya,
    [Description("Сквозной")] Skvoznaya,
    [Description("Складская")] Skladskaya,
    [Description("Славы")] Slava,
    [Description("Советская")] Sovetskaya,
    [Description("Соколовская")] Sokolovskaya,
    [Description("Солнечная")] Solnechnaya,
    [Description("Солнечный бульвар")] SolnechnyyBulvar,
    [Description("Сопочная")] Sopochnaya,
    [Description("Софьи Ковалевской")] SofiyaKovalyovskoy,
    [Description("Спандаряна")] Spandaryana,
    [Description("Спартаковцев")] Spartakovtsyev,
    [Description("Спортивная")] Sportivnaya,
    [Description("Средний")] Sredniy,
    [Description("Станочная")] Stanochnaya,
    [Description("Степана Разина")] StepanaRazina,
    [Description("Стрелочная")] Strelochnaya,
    [Description("Судостроительная")] Sudostroitelnaya,
    [Description("Сурикова")] Surykova,
    [Description("Тамбовская")] Tambovskaya,
    [Description("Текстильщиков")] Tekstilshchikov,
    [Description("Тельмана")] Telmana,
    [Description("Теплый")] Teplyy,
    [Description("Терешковой")] Tereshkovo,
    [Description("Тимирязева")] Timiryazeva,
    [Description("Тихий")] Tikhoy,
    [Description("Тихоновская")] Tihonovskaya,
    [Description("Тобольская")] Tobolskaya,
    [Description("Толстого")] Tolstogo,
    [Description("Тотмина")] Totmina,
    [Description("Транзитная")] Tranzitnaya,
    [Description("Туманный")] Tumanyy,
    [Description("Угловой")] Uglovoi,
    [Description("Удачная")] Udachnaya,
    [Description("Ульяновский")] Ulyanovskoy,
    [Description("Урванцева")] Urvanzheva,
    [Description("Урицкого")] Urtskogo,
    [Description("Устиновича")] Ustinovicha,
    [Description("Учумская")] Uchumskaya,
    [Description("Уютный")] Uytnyy,
    [Description("Ферганская")] Ferganskaya,
    [Description("Фестивальная")] Festivnalnaya,
    [Description("Фруктовая")] Fruktovaya,
    [Description("Фрунзе")] Frunze,
    [Description("Хабаровская 1-я")] Habarovskaya1,
    [Description("Хабаровская 2-я")] Habarovskaya2,
    [Description("Хетская")] Hetskaya,
    [Description("Храпова")] Hrapova,
    [Description("Хрустальная")] Khrustralnaya,
    [Description("Цветной бульвар")] TsvetniiBulvar,
    [Description("Центральный проезд")] CenralnyyProezd,
    [Description("Цимлянская")] Cimlyanskaya,
    [Description("Чайковского")] Chajkovskogo,
    [Description("Черепнина")] Cherepnina,
    [Description("Чернышева")] Chernysheva,
    [Description("Чернышевского")] Chernyshovskogo,
    [Description("Чистопрудная")] Chistoprudnaya,
    [Description("Читинская")] Chitinskaya,
    [Description("Чкалова")] Chkalova,
    [Description("Шахтеров")] Shakhterov,
    [Description("Шевченко")] Shevchenko,
    [Description("Шелковая")] Shelkovaya,
    [Description("Шинная")] Shinnaya,
    [Description("Ширинская")] Shirinskaya,
    [Description("Школьный")] Shkolnyy,
    [Description("Шумяцкого")] Shumyatskogo,
    [Description("Щербакова")] Shcherbakova,
    [Description("Щетинкина")] Shchetinkina,
    [Description("Щорса")] Shorsa,
    [Description("Электриков")] Elektrikov,
    [Description("Энергетиков")] Energetikov,
    [Description("Юности")] Yunti,
    [Description("Юшкова")] Yushkova,
    [Description("Яблочкова")] Yablochkov,
    [Description("Яковлева")] Yakovleva,
    [Description("Якорный")] Jakorny,
    [Description("Ярцевский")] Yartsevskoy,
    [Description("Ярыгинская набережная")] YaryginskayaNaberezhnaya,
    [Description("Ястынская")] Yastynskaya
}